---
abstract: 'NetAddr::IP new() methods with no validation'
author:
  - 'Robert Drake <rdrake@cpan.org>'
build_requires:
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NetAddr-IP-FastNew
no_index:
  directory:
    - inc
requires:
  NetAddr::IP: '0'
  NetAddr::IP::Util: '0'
  Socket: '1.95'
  perl: v5.12.5
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/rfdrake/NetAddr-IP-FastNew/issues
  homepage: http://search.cpan.org/dist/NetAddr-IP-FastNew
  repository: git://github.com/rfdrake/NetAddr-IP-FastNew.git
version: '0.3'
